### ISSUE TITLE
how to start?  run prepare.py  failed!

### ISSUE THREAD

**Issue by andyyuan78** [yvesx/CRF_sentiment#1]
envy@ub1404envy:~/os_prj/github/_crf/CRF_sentiment$ 
envy@ub1404envy:~/os_prj/github/_crf/CRF_sentiment$ sudo  python ./prepare.py 
ERROR! Unable to load "zh" dictionary in ./keyword_list/keyword_list_cn/
ERROR! Unable to load "en" dictionary in ./keyword_list/keyword_list_en/
ERROR! Unable to load "fr" dictionary in ./keyword_list/keyword_list_fr/
ERROR! Unable to load "ge" dictionary in ./keyword_list/keyword_list_ge/
ERROR! Unable to load "kr" dictionary in ./keyword_list/keyword_list_kr/
ERROR! Unable to load "po" dictionary in ./keyword_list/keyword_list_po/
ERROR! Unable to load "ro" dictionary in ./keyword_list/keyword_list_ro/
ERROR! Unable to load "sp" dictionary in ./keyword_list/keyword_list_sp/
doc 13
LSI trained
processing 0
Traceback (most recent call last):
  File "./prepare.py", line 282, in <module>
    init()
  File "./prepare.py", line 86, in init
    getFeatures()
  File "./prepare.py", line 169, in getFeatures
    array = set(word_tokenize(sentence))
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/__init__.py", line 104, in word_tokenize
    return [token for sent in sent_tokenize(text, language)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/**init**.py", line 88, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 796, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 914, in _open
    return find(path_, path + ['']).open()
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 636, in find
    raise LookupError(resource_not_found)
LookupError: 

---

  Resource u'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/envy/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''

---

envy@ub1404envy:~/os_prj/github/_crf/CRF_sentiment$

**Comment by andyyuan78** [comment]
need nltk data
